ansh_dbt_youtube:
  target: dev                     # default target when you just run "dbt run"
  outputs:
    dev:
      type: databricks
      catalog: dbt_tutorial_dev     # ← hard-code the catalog name
      schema: default
      host: dbc-a749e477-8292.cloud.databricks.com
      http_path: /sql/1.0/warehouses/62dabd124f879007
      token: {{ env_var('DBT_DATABRICKS_TOKEN_DEV') }}
      threads: 1

    prod:
      type: databricks
      catalog: dbt_tutorial_prod    # or whatever your production catalog is
      schema: default
      host: dbc-a749e477-8292.cloud.databricks.com   # usually same cluster/warehouse
      http_path: /sql/1.0/warehouses/62dabd124f879007
      token: {{ env_var('DBT_DATABRICKS_TOKEN_PROD') }}   # use a different token or service principal in prod!
      threads: 4